[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.65.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build:preview"
